name: Docker Image CI

on: 
  push:
    branches: 
      - develop
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build & push the Docker image
      run: |
          docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
          docker build --tag huntsmanarray/device_startup:latest \
            --output "type=image,push=true" \
            --file docker/device_startup.docker .
